package corba.hotelbooking;

/**
* corba/hotelbooking/HotelWMHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HotelWM.idl
* Saturday, May 16, 2015 4:28:13 PM CST
*/

public final class HotelWMHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.hotelbooking.HotelWM value = null;

  public HotelWMHolder ()
  {
  }

  public HotelWMHolder (corba.hotelbooking.HotelWM initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.hotelbooking.HotelWMHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.hotelbooking.HotelWMHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.hotelbooking.HotelWMHelper.type ();
  }

}
