package corba.hotelbooking;


/**
* corba/hotelbooking/HotelWMOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HotelWM.idl
* Saturday, May 16, 2015 4:28:13 PM CST
*/

public interface HotelWMOperations 
{
  String queryHotel (String req);
  String queryRoomrate (String req);
  String queryVacancy (String req);
  String queryRoomId (String req);
  String booking (String req);
  String queryBook (String req);
} // interface HotelWMOperations
