package corba.hotelbooking;


/**
* corba/hotelbooking/HotelWMHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HotelWM.idl
* Saturday, May 16, 2015 4:28:13 PM CST
*/

abstract public class HotelWMHelper
{
  private static String  _id = "IDL:corba/hotelbooking/HotelWM:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.hotelbooking.HotelWM that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.hotelbooking.HotelWM extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.hotelbooking.HotelWMHelper.id (), "HotelWM");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.hotelbooking.HotelWM read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HotelWMStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.hotelbooking.HotelWM value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.hotelbooking.HotelWM narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.hotelbooking.HotelWM)
      return (corba.hotelbooking.HotelWM)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba.hotelbooking._HotelWMStub stub = new corba.hotelbooking._HotelWMStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.hotelbooking.HotelWM unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.hotelbooking.HotelWM)
      return (corba.hotelbooking.HotelWM)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba.hotelbooking._HotelWMStub stub = new corba.hotelbooking._HotelWMStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
