package corba.hotelbooking;


/**
* corba/hotelbooking/HotelWM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HotelWM.idl
* Saturday, May 16, 2015 4:28:13 PM CST
*/

public interface HotelWM extends HotelWMOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HotelWM
